ministryofjustice/hmpps-prisoner-events

- .circleci/config.yml
- helm_deploy/hmpps-prisoner-events/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/config/JMSConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/xtag/XtagContent.kt
> SDI-333 Changes to event handling to improve latency

- helm_deploy/hmpps-prisoner-events/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/config/JMSConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/JMSReceiver.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/JMSReceiverTest.kt
- src/test/resources/application-test.yml
> SDI-415 Events delivered before replica is updated

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/model/OffenderEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/JMSReceiver.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/XtagEventsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/xtag/XtagContent.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/JMSReceiverTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/XtagEventsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformerTest.kt
- src/test/resources/application-test.yml
Map the new case notes event
Also remove an old timestamp feature switch
> SDI-450 removal of the /events endpoint from prison api

- build.gradle.kts
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/repository/SqlRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/AQService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/PrisonEventsEmitter.kt
- src/main/resources/db/migration/V1_70__XTAG_LISTENER_TAB.sql
- src/main/resources/logback-spring.xml
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/helper/JwtAuthHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/integration/OracleToTopicIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/PrisonEventsEmitterTest.kt
> SDIT-643 Allow retry of failed prison events

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/model/OffenderEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformer.kt
- src/main/resources/swagger-description.html
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformerTest.kt
Remove 1 of the 2 non-association events as they always occur together
> SDIT-707 Create prison events from XTag events

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/model/OffenderEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformerTest.kt
- src/test/resources/application-test.yml
Process the new event for cancelling appointments on transfer or release
> SDIT-868 Handle Appointments for Transfers

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/model/OffenderEvent.kt
- src/main/resources/db/migration/V1_450__XTAG_LISTENER_TAB.sql
- src/main/resources/logback-spring.xml
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/integration/OracleContainerConfig.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/integration/OracleToTopicIntTest.kt
Logging of transactions and minor tweaks
> SDIT-640 Retry and alert on Oracle AQ events queue

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/AQService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/PrisonEventsEmitter.kt
Move custom event to use for app insights alert
> SDIT-953 Add alert for the Oracle event exception queue

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/model/OffenderEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/repository/SqlRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/XtagEventsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/repository/SqlRepositoryTest.kt
Since this is not in the trigger, until they are added just retrieve from database
> SDIT-1805 Add username to ContactOffenderEvent

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/repository/SqlRepository.kt
> SDIT-1820 Add queue count to info endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/health/QueueHealthInfo.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/repository/SqlRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/AQService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/integration/health/QueueHealthInfoTest.kt
Causes performance issues in prod
> SDIT-1820 Remove queue count from info endpoint

- build.gradle.kts
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/config/JMSConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/JMSReceiver.kt
This reverts commit 2b77823f3c02a990b27ac0ef1f87730745fc6ea5.
> Revert "SDIT-1820 Revert concurrent consumers (#209)"

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
> SDIT-1820 Scale down threads to 1 per pod

- build.gradle.kts
- SDIT-1919 Use Gradle Spring Boot plugin version 6.0.2
- SDIT-1919 Use Gradle Spring Boot plugin version 6.0.2
> mh SDIT 1919 latest spring boot plugin

- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/integration/OracleToTopicIntTest.kt
- src/test/resources/application-test.yml
TODO:
1) Add person Id and assert
2) Improve database seed of prisoner data
> SDIT-1923 Improve integration test

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/repository/Offender.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/repository/OffenderBookings.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/repository/OffenderContactRestriction.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/repository/Person.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/integration/OracleToTopicIntTest.kt
Switched to Java date time from kotlin library
> SDIT-1923 Add person id for PERSON_RESTRICTION-UPSERTED

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/model/OffenderEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/integration/OracleToTopicIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/XtagEventsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformerTest.kt
Not needed and expose too much person data
> SDIT-1923 Removed comment from restriction events

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/XtagEventsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformer.kt
add debug for jus timestamp analysis
> Sdit 1982 booking number changed

- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/repository/ExposeRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/XtagEventsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/integration/OracleToTopicIntTest.kt
…
Either OFFENDER_ID_DISPLAY_1 or OFFENDER_ID_DISPLAY_2 points to the retained offenderNo depending on the age of the record.
> SDIT-1982 Fix BOOKING_NUMBER-CHANGED to return correct retained offenderNo

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/model/OffenderEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/xtag/XtagContent.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformerTest.kt
Shamelessly copied from offender images
> SDIT-2147 person tag images

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/model/OffenderEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformerTest.kt
Convert LINK_CASE_TXNS-DELETED/INSERTED to the linked equivalent when xtag is result of a linking operation
> SDIT-2718 COURT_EVENT_CHARGES-LINKED and COURT_EVENT_CHARGES-UNLINKED

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/model/OffenderEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/xtag/XtagContent.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformerTest.kt
Generate health and language events
> SDIT-2742-Add-care-needs,-smoking-and-languages-fields-to-prisoner-search

- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/model/OffenderEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/xtag/XtagContent.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/service/transformers/OffenderEventsTransformerTest.kt
So that sync knows when a DPS recall has added a breach hearing
> SDIT-2837 Add isBreachHearing to COURT_EVENTS-*

- src/test/kotlin/uk/gov/justice/digital/hmpps/prisonerevents/integration/OraclePoolingIntTest.kt
- **SDIT-2997: ⬆️  Upgrade for netty fix & kotlin 2.2.10**
- **SDIT-2997: ✅ Amend test after upgrade of spring jms & oracle database messaging**
- **SDIT-2997: ✅ Fix comment for test**
> SDIT-2997: ✅ Fix comment for test
